# Basic config
#baseURL = "https://soeren.me/"
baseURL = "https://s01ren.github.io/Blog/"
title = "Soren's Blog"

theme = "simple-soeren"

languageCode = "en-US"


[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Slashes"
pageRef = "/slashes"
weight = 20


defaultContentLanguage = 'en'
[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageName = 'read in English'
    weight = 1
  [languages.de]
    disabled = false
    languageCode = 'de-DE'
    languageName = 'in Deutsch lesen'
  