# Basic config
#baseURL = "https://gluecko.se"
baseURL = "https://s01ren.github.io/Blog/"
title = "gluecko.se"

theme = "simple-soeren"

languageCode = "en-US"


[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Slashes"
pageRef = "/slashes"
weight = 20
[[menu.main]]
name = "About"
pageRef = "/about"
weight = 30
[[menu.main]]
name = "Contact"
pageRef = "/contact"
weight = 40


defaultContentLanguage = 'en'
[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageName = 'read in English'
    weight = 1
  [languages.de]
    disabled = false
    languageCode = 'de-DE'
    languageName = 'in Deutsch lesen'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # allow HTML in MD files